"""Auto-generated SoA form field metadata.

Do not edit manually. Run `python scripts/generate_soa_assets.py`.
"""
from __future__ import annotations

SOA_FORM_FIELD_METADATA: dict[str, list[dict[str, object]]] = {
    'deposits': [
        {'name': 'financial_institution', 'placeholder': '例：〇〇銀行', 'autofocus': True},
        {'name': 'branch_name', 'placeholder': '例：本店'},
        {'name': 'account_type', 'type': 'select'},
        {'name': 'account_number', 'placeholder': '例：1234567'},
        {'name': 'balance', 'placeholder': '例：1000000', 'type': 'money'},
        {'name': 'remarks', 'placeholder': '摘要を入力（任意）', 'type': 'text'},
    ],
    'notes_receivable': [
        {'name': 'drawer', 'placeholder': '例：株式会社〇〇商事', 'autofocus': True},
        {'name': 'registration_number', 'placeholder': '例：1234567890123', 'type': 'corporate_number'},
        {'name': 'issue_date', 'type': 'date'},
        {'name': 'due_date', 'type': 'date'},
        {'name': 'payer_bank', 'placeholder': '例：〇〇銀行'},
        {'name': 'payer_branch', 'placeholder': '例：本店'},
        {'name': 'amount', 'placeholder': '例：500000', 'type': 'money'},
        {'name': 'discount_bank', 'placeholder': '例：△△銀行（任意）'},
        {'name': 'discount_branch', 'placeholder': '例：新宿支店（任意）'},
        {'name': 'remarks', 'placeholder': '摘要（任意）', 'type': 'text'},
    ],
    'accounts_receivable': [
        {'name': 'account_name', 'type': 'select'},
        {'name': 'registration_number', 'placeholder': '例：1234567890123', 'type': 'corporate_number'},
        {'name': 'partner_name', 'placeholder': '例：株式会社 △△商会'},
        {'name': 'partner_address', 'placeholder': '例：東京都千代田区〇〇町1-2-3', 'type': 'text'},
        {'name': 'balance_at_eoy', 'placeholder': '例：500000', 'type': 'money'},
        {'name': 'remarks', 'placeholder': '例：商品Aの売上代金', 'type': 'text'},
    ],
    'temporary_payments': [
        {'name': 'account_name', 'type': 'select'},
        {'name': 'registration_number', 'placeholder': '例：1234567890123', 'type': 'corporate_number'},
        {'name': 'partner_name', 'placeholder': '例：株式会社 □□'},
        {'name': 'partner_address', 'placeholder': '例：東京都中央区〇〇1-2-3', 'type': 'text'},
        {'name': 'relationship', 'placeholder': '例：代表者の子会社'},
        {'name': 'balance_at_eoy', 'placeholder': '例：300000', 'type': 'money'},
        {'name': 'transaction_details', 'placeholder': '例：出張旅費の仮払い', 'type': 'text'},
    ],
    'loans_receivable': [
        {'name': 'registration_number', 'placeholder': '例：1234567890123', 'autofocus': True, 'type': 'corporate_number'},
        {'name': 'borrower_name', 'placeholder': '例：株式会社 〇〇商事'},
        {'name': 'borrower_address', 'placeholder': '例：東京都千代田区〇〇1-2-3', 'type': 'text'},
        {'name': 'relationship', 'placeholder': '例：代表者の親族会社'},
        {'name': 'balance_at_eoy', 'placeholder': '例：300000', 'type': 'money'},
        {'name': 'received_interest', 'placeholder': '例：15000', 'type': 'money'},
        {'name': 'interest_rate', 'placeholder': '例：2.0', 'type': 'percent'},
        {'name': 'collateral_details', 'placeholder': '例：不動産（東京都港区…）', 'type': 'text'},
    ],
    'inventories': [
        {'name': 'item_name', 'autofocus': True},
        {'name': 'location'},
        {'name': 'quantity', 'type': 'float'},
        {'name': 'unit'},
        {'name': 'unit_price', 'type': 'money'},
        {'name': 'balance_at_eoy', 'type': 'money'},
        {'name': 'remarks', 'type': 'text'},
    ],
    'securities': [
        {'name': 'security_type', 'autofocus': True},
        {'name': 'issuer'},
        {'name': 'quantity', 'type': 'integer'},
        {'name': 'balance_at_eoy', 'type': 'money'},
        {'name': 'remarks', 'type': 'text'},
    ],
    'fixed_assets': [
        {'name': 'asset_type', 'autofocus': True},
        {'name': 'location'},
        {'name': 'area', 'type': 'float'},
        {'name': 'balance_at_eoy', 'type': 'money'},
        {'name': 'remarks', 'type': 'text'},
    ],
    'notes_payable': [
        {'name': 'registration_number', 'placeholder': '例：1234567890123', 'type': 'corporate_number'},
        {'name': 'payee', 'placeholder': '例：株式会社△△', 'autofocus': True},
        {'name': 'issue_date', 'type': 'date'},
        {'name': 'due_date', 'type': 'date'},
        {'name': 'payer_bank', 'placeholder': '例：〇〇銀行'},
        {'name': 'payer_branch', 'placeholder': '例：本店'},
        {'name': 'amount', 'placeholder': '例：300000', 'type': 'money'},
        {'name': 'remarks', 'placeholder': '摘要（任意）', 'type': 'text'},
    ],
    'accounts_payable': [
        {'name': 'registration_number', 'placeholder': '例：1234567890123', 'autofocus': True, 'type': 'corporate_number'},
        {'name': 'partner_name', 'placeholder': '例：株式会社〇〇商事（または氏名）'},
        {'name': 'partner_address', 'placeholder': '例：東京都千代田区丸の内…', 'type': 'text'},
        {'name': 'balance_at_eoy', 'placeholder': '例：1000000', 'type': 'money'},
        {'name': 'remarks', 'placeholder': '例：仕入代金', 'type': 'text'},
    ],
    'temporary_receipts': [
        {'name': 'account_name', 'placeholder': '例：預り金', 'autofocus': True},
        {'name': 'partner_name', 'placeholder': '例：株式会社 △△'},
        {'name': 'balance_at_eoy', 'placeholder': '例：100000', 'type': 'money'},
        {'name': 'transaction_details', 'placeholder': '例：保証金の預り', 'type': 'text'},
    ],
    'borrowings': [
        {'name': 'lender_name', 'placeholder': '例：〇〇銀行', 'autofocus': True},
        {'name': 'is_subsidiary', 'type': 'boolean'},
        {'name': 'balance_at_eoy', 'placeholder': '例：5000000', 'type': 'money'},
        {'name': 'interest_rate', 'placeholder': '例：1.8', 'type': 'percent'},
        {'name': 'paid_interest', 'placeholder': '例：120000', 'type': 'money'},
        {'name': 'remarks', 'placeholder': '例：設備投資のため', 'type': 'text'},
    ],
    'executive_compensations': [
        {'name': 'shareholder_name', 'placeholder': '例：山田 太郎', 'autofocus': True},
        {'name': 'relationship', 'placeholder': '例：代表取締役'},
        {'name': 'position', 'placeholder': '例：代表取締役社長'},
        {'name': 'base_salary', 'placeholder': '例：500000', 'type': 'money'},
        {'name': 'other_allowances', 'placeholder': '例：役員賞与は無し', 'type': 'money'},
        {'name': 'total_compensation', 'placeholder': '例：600000', 'type': 'money'},
    ],
    'land_rents': [
        {'name': 'account_name', 'autofocus': True, 'type': 'select'},
        {'name': 'lessor_name', 'placeholder': '例：〇〇不動産'},
        {'name': 'property_details', 'placeholder': '例：東京都港区六本木6-10-1', 'type': 'text'},
        {'name': 'rent_paid', 'placeholder': '例：200000', 'type': 'money'},
        {'name': 'remarks', 'placeholder': '例：本店オフィス賃料', 'type': 'text'},
    ],
    'misc_income': [
        {'name': 'account_name', 'type': 'hidden'},
        {'name': 'details', 'placeholder': '例：内容', 'type': 'text'},
        {'name': 'amount', 'placeholder': '例：金額', 'type': 'money'},
        {'name': 'remarks', 'placeholder': '摘要（任意）', 'type': 'text'},
    ],
    'misc_losses': [
        {'name': 'account_name', 'type': 'hidden'},
        {'name': 'details', 'placeholder': '例：内容', 'type': 'text'},
        {'name': 'amount', 'placeholder': '例：金額', 'type': 'money'},
        {'name': 'remarks', 'placeholder': '摘要（任意）', 'type': 'text'},
    ],
}

__all__ = ['SOA_FORM_FIELD_METADATA']
