"""Add email column to User model

Revision ID: 31722a09f46e
Revises: 4d076bbb4efb
Create Date: 2025-08-13 12:33:28.142266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31722a09f46e'
down_revision = '4d076bbb4efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # ステップ1: NULLを許容する形でemailカラムを追加
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ステップ2: 既存のユーザーに仮のメールアドレスを設定
    op.execute("UPDATE user SET email = username || '@example.com' WHERE email IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        # ステップ3: NOT NULL制約を追加し、インデックスを作成
        batch_op.alter_column('email', nullable=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
