"""Add MasterVersion model

Revision ID: 3dc586dd6091
Revises: 97f95146b0e3
Create Date: 2025-08-10 11:05:28.392628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc586dd6091'
down_revision = '97f95146b0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_statements_store')
    op.drop_table('unmatched_accounts_store')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('first_name_kana')
        batch_op.drop_column('last_name_kana')

    with op.batch_alter_table('user_account_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('_user_software_original_account_uc', type_='unique')
        batch_op.drop_index('ix_user_account_mapping_software_name')
        batch_op.create_unique_constraint('_user_original_account_uc', ['user_id', 'original_account_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('_user_original_account_uc', type_='unique')
        batch_op.create_index('ix_user_account_mapping_software_name', ['software_name'], unique=False)
        batch_op.create_unique_constraint('_user_software_original_account_uc', ['user_id', 'software_name', 'original_account_name'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name_kana', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('first_name_kana', sa.VARCHAR(length=50), nullable=True))

    op.create_table('unmatched_accounts_store',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_statements_store',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
