"""Rename employee_name to shareholder_name in ExecutiveCompensation

Revision ID: 47f61b953ac6
Revises: 6c9457f40656
Create Date: 2025-08-11 13:49:33.879216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f61b953ac6'
down_revision = '6c9457f40656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executive_compensation', schema=None) as batch_op:
        batch_op.alter_column('employee_name', new_column_name='shareholder_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executive_compensation', schema=None) as batch_op:
        batch_op.alter_column('shareholder_name', new_column_name='employee_name')

    # ### end Alembic commands ###
