"""Add constraints and columns to shareholder

Revision ID: 4d076bbb4efb
Revises: 71f6d8f1b56b
Create Date: 2025-08-13 12:06:07.427640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d076bbb4efb'
down_revision = '71f6d8f1b56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_officer', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('fk_shareholder_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('investment_amount')
        batch_op.drop_column('prefecture_city')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('is_controlled_company')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
