"""Add name column to office table

Revision ID: 56166e3817d1
Revises: f3b65fbd6f00
Create Date: 2025-08-04 22:39:40.267759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56166e3817d1'
down_revision = 'f3b65fbd6f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False, server_default='（名称未設定）'))
        batch_op.add_column(sa.Column('municipality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('office_count', sa.Integer(), nullable=True))
        batch_op.alter_column('opening_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('closing_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_column('office_name')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('office_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('closing_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('opening_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('office_count')
        batch_op.drop_column('municipality')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
