"""Rename Employee to Shareholder

Revision ID: 6c9457f40656
Revises: 73efda238356
Create Date: 2025-08-11 13:46:42.274190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9457f40656'
down_revision = '73efda238356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('employee', 'shareholder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('shareholder', 'employee')
    # ### end Alembic commands ###
