"""Add address components to Shareholder

Revision ID: 71f6d8f1b56b
Revises: f4f5494df524
Create Date: 2025-08-12 18:41:07.705536

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '71f6d8f1b56b'
down_revision = 'f4f5494df524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('zip_code', sa.String(length=8), nullable=True))
        # batch_op.add_column(sa.Column('prefecture_city', sa.String(length=100), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.drop_column('prefecture_city')
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
