"""Add address components to Shareholder

Revision ID: 71f6d8f1b56b
Revises: f4f5494df524
Create Date: 2025-08-12 18:41:07.705536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f6d8f1b56b'
down_revision = 'f4f5494df524'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {col['name'] for col in inspector.get_columns('shareholder')}

    if 'zip_code' not in columns:
        op.add_column('shareholder', sa.Column('zip_code', sa.String(length=7), nullable=True))
    if 'prefecture_city' not in columns:
        op.add_column('shareholder', sa.Column('prefecture_city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.drop_column('prefecture_city')
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
