"""Add is_excluded_business to Company

Revision ID: 73efda238356
Revises: 7bf204eefd20
Create Date: 2025-08-10 20:28:36.614574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73efda238356'
down_revision = '7bf204eefd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_hash')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_excluded_business', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('is_excluded_business')

    op.drop_table('master_version')
    # ### end Alembic commands ###
