"""Add user_id to Company model

Revision ID: 7bf204eefd20
Revises: 3dc586dd6091
Create Date: 2025-08-10 20:20:31.395120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf204eefd20'
down_revision = '3dc586dd6091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_company_user_id', 'user', ['user_id'], ['id'])

    # データ移行: 既存の会社にデフォルトユーザー(id=1)を割り当てる
    op.execute('UPDATE company SET user_id = 1 WHERE user_id IS NULL')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint('fk_company_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
