"""Change zip_code length in Shareholder and Office models

Revision ID: 8d675e777cd4
Revises: 31722a09f46e
Create Date: 2025-08-13 14:26:08.503778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d675e777cd4'
down_revision = '31722a09f46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=7),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
