"""Revert accounting period columns to String type

Revision ID: ae7691c8e63f
Revises: db7780bdc863
Create Date: 2025-08-16 22:00:09.709701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7691c8e63f'
down_revision = 'db7780bdc863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('accounting_period_start',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('accounting_period_end',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('accounting_period_end',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('accounting_period_start',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
