"""Database schema migration.

Revision ID: c153aab08c82
Revises: d930b864adb7
Create Date: 2025-09-21 00:30:58.135098
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c153aab08c82'
down_revision = 'd930b864adb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_tax_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_start_date', sa.Date(), nullable=False),
    sa.Column('fiscal_end_date', sa.Date(), nullable=False),
    sa.Column('months_standard', sa.Integer(), nullable=False),
    sa.Column('months_truncated', sa.Integer(), nullable=False),
    sa.Column('corporate_tax_rate_u8m', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('corporate_tax_rate_o8m', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('local_corporate_tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('enterprise_tax_rate_u4m', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('enterprise_tax_rate_4m_8m', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('enterprise_tax_rate_o8m', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('local_special_tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('prefectural_corporate_tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('prefectural_equalization_amount', sa.Integer(), nullable=False),
    sa.Column('municipal_corporate_tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('municipal_equalization_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_start_date', name='ux_corporate_tax_master_fiscal_start')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corporate_tax_master')
    # ### end Alembic commands ###
