"""Change User-Company relationship to one-to-one

Revision ID: c48f2abe8868
Revises: ae7691c8e63f
Create Date: 2025-08-16 22:12:27.323676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48f2abe8868'
down_revision = 'ae7691c8e63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_company_user_id", ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint("uq_company_user_id", type_='unique')

    # ### end Alembic commands ###
