"""Rename is_officer to is_controlled_company in Shareholder

Revision ID: d70af01038af
Revises: 91859660db66
Create Date: 2025-08-12 00:06:07.647579

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd70af01038af'
down_revision = '91859660db66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.alter_column('is_officer', new_column_name='is_controlled_company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.alter_column('is_controlled_company', new_column_name='is_officer')

    # ### end Alembic commands ###
