"""add_is_admin_flag_to_user

Revision ID: d930b864adb7
Revises: f3a4b5c6d7e8
Create Date: 2025-09-20 23:12:20.712937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd930b864adb7'
down_revision = 'f3a4b5c6d7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_signup_tokens_user_id')
        batch_op.drop_index('ux_signup_tokens_token_hash')

    op.drop_table('signup_tokens')
    with op.batch_alter_table('reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_reset_tokens_user_id')
        batch_op.drop_index('ux_reset_tokens_token_hash')

    op.drop_table('reset_tokens')
    with op.batch_alter_table('accounts_payable', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_payable_company_id')

    with op.batch_alter_table('accounts_receivable', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_receivable_company_id')

    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.alter_column('paid_interest',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index('ix_borrowing_company_id')

    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.drop_index('ix_deposit_company_id')

    with op.batch_alter_table('executive_compensation', schema=None) as batch_op:
        batch_op.drop_index('ix_executive_compensation_company_id')

    with op.batch_alter_table('fixed_asset', schema=None) as batch_op:
        batch_op.drop_index('ix_fixed_asset_company_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_company_id')

    with op.batch_alter_table('land_rent', schema=None) as batch_op:
        batch_op.drop_index('ix_land_rent_company_id')

    with op.batch_alter_table('loans_receivable', schema=None) as batch_op:
        batch_op.alter_column('received_interest',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index('ix_loans_receivable_company_id')
        batch_op.drop_column('is_subsidiary')

    with op.batch_alter_table('miscellaneous', schema=None) as batch_op:
        batch_op.drop_index('ix_miscellaneous_company_id')

    with op.batch_alter_table('notes_payable', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_payable_company_id')

    with op.batch_alter_table('notes_receivable', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_receivable_company_id')

    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.drop_index('ix_office_company_id')

    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.drop_index('ix_security_company_id')

    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.drop_index('ix_shareholder_company_id')

    with op.batch_alter_table('temporary_payment', schema=None) as batch_op:
        batch_op.drop_index('ix_temporary_payment_company_id')

    with op.batch_alter_table('temporary_receipt', schema=None) as batch_op:
        batch_op.drop_index('ix_temporary_receipt_company_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('temporary_receipt', schema=None) as batch_op:
        batch_op.create_index('ix_temporary_receipt_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('temporary_payment', schema=None) as batch_op:
        batch_op.create_index('ix_temporary_payment_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.create_index('ix_shareholder_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.create_index('ix_security_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.create_index('ix_office_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('notes_receivable', schema=None) as batch_op:
        batch_op.create_index('ix_notes_receivable_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('notes_payable', schema=None) as batch_op:
        batch_op.create_index('ix_notes_payable_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('miscellaneous', schema=None) as batch_op:
        batch_op.create_index('ix_miscellaneous_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('loans_receivable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subsidiary', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_loans_receivable_company_id', ['company_id'], unique=False)
        batch_op.alter_column('received_interest',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('land_rent', schema=None) as batch_op:
        batch_op.create_index('ix_land_rent_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('fixed_asset', schema=None) as batch_op:
        batch_op.create_index('ix_fixed_asset_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('executive_compensation', schema=None) as batch_op:
        batch_op.create_index('ix_executive_compensation_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.create_index('ix_deposit_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.create_index('ix_borrowing_company_id', ['company_id'], unique=False)
        batch_op.alter_column('paid_interest',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('accounts_receivable', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_receivable_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('accounts_payable', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_payable_company_id', ['company_id'], unique=False)

    op.create_table('reset_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reset_tokens', schema=None) as batch_op:
        batch_op.create_index('ux_reset_tokens_token_hash', ['token_hash'], unique=1)
        batch_op.create_index('ix_reset_tokens_user_id', ['user_id'], unique=False)

    op.create_table('signup_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signup_tokens', schema=None) as batch_op:
        batch_op.create_index('ux_signup_tokens_token_hash', ['token_hash'], unique=1)
        batch_op.create_index('ix_signup_tokens_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
