"""Database schema migration: add is_admin flag to user and remove legacy token tables.

Revision ID: d930b864adb7
Revises: f3a4b5c6d7e8
Create Date: 2025-09-20 23:12:20.712937
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd930b864adb7'
down_revision = 'f3a4b5c6d7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_signup_tokens_user_id')
        batch_op.drop_index('ux_signup_tokens_token_hash')

    op.drop_table('signup_tokens')
    with op.batch_alter_table('reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_reset_tokens_user_id')
        batch_op.drop_index('ux_reset_tokens_token_hash')

    op.drop_table('reset_tokens')
    with op.batch_alter_table('accounts_payable', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_payable_company_id')

    with op.batch_alter_table('accounts_receivable', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_receivable_company_id')

    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.alter_column('paid_interest',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('loans_receivable', schema=None) as batch_op:
        batch_op.alter_column('received_interest',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('loans_receivable', schema=None) as batch_op:
        batch_op.alter_column('received_interest',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.alter_column('paid_interest',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('accounts_receivable', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_receivable_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('accounts_payable', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_payable_company_id', ['company_id'], unique=False)

    op.create_table('reset_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_reset_tokens_token_hash', 'reset_tokens', ['token_hash'], unique=True)
    op.create_index('ix_reset_tokens_user_id', 'reset_tokens', ['user_id'], unique=False)
    op.create_table('signup_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_signup_tokens_token_hash', 'signup_tokens', ['token_hash'], unique=True)
    op.create_index('ix_signup_tokens_user_id', 'signup_tokens', ['user_id'], unique=False)

    # ### end Alembic commands ###
