"""Add parent_id and investment_amount to Shareholder

Revision ID: f4f5494df524
Revises: d70af01038af
Create Date: 2025-08-12 17:01:27.473797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f5494df524'
down_revision = 'd70af01038af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_shareholder_parent_id', 'shareholder', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shareholder_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('investment_amount')

    # ### end Alembic commands ###
